Second test after auth fail.
